spring:
  application:
    name: pdfGenerator
  ai:
    openai:
      chat:
#        completions-path: /v1/completions
        options:
          model: gpt-4o
      api-key: ${Open-AI_key}

  datasource:
    url: jdbc:postgresql://localhost:${datasource_port}/Resume
    username: ${datasource_userName}
    password: ${datasource_password}
    driver-class-yml: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migration: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${datasource_userName}
    password: ${datasource_password}

springdoc:
  api-docs:
    path:
      /v3/api-docs
  swagger-ui:
    path:
      swagger-ui.html

server:
  port:
    ${port}